stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
      - CI
  script:
    - az login
    - az acr login --name kdcommonacr1
    #- sudo docker build -t kdjavarestapi1:latest .
    #- sudo docker image ls
    #- az 

