stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
      - CI
  script:
    - ls
    - docker build -t kdjavarestapi1:latest .
    - docker image ls

